[package]
name = "cp-rust"
version = "0.1.0"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "4a"
path = "src/codeforces/4a.rs"