[package]
name = "cp-rust"
version = "0.0.1"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn>"]
edition = "2018"
default-run = "cp-rust"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
dotenv = "0.15.0"
fantoccini = "0.12.0-alpha.4"
tokio = "0.2.0-alpha.6" 