[package]
name = "cp-rust"
version = "0.0.1"
authors = ["Gabriel Wu <wuzihua@pku.edu.cn>"]
edition = "2018"
default-run = "cp-rust"
autobins = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap" }
data-encoding = "2.1.2"  
dotenv = "0.15.0"
fantoccini = "0.12.0-alpha.4"
rand = "0.7.2"
reqwest = "0.9.22"
ring = "0.16.9"
serde = "1.0.101"
serde_json = "1.0"
sysinfo = "0.9.5"
tokio = "0.2.0-alpha.6" 